apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: ham-deployable-operator
    app.kubernetes.io/managed-by: ham-deployable-operator
    app.kubernetes.io/name: hybridApplication
  name: ham-deployable-operator
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - core.hybridapp.io
  resources:
  - '*'
  - deployers
  - deployersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
