apiVersion: v1
kind: ServiceAccount
metadata:
  name: ham-deployable-operator
  labels:
    app.kubernetes.io/instance: ham-deployable-operator
    app.kubernetes.io/managed-by: ham-deployable-operator
    app.kubernetes.io/name: hybridApplication
